
volumes:
  influxdb_data:
  grafana_data:

networks:
  pubel:

services:
  prusa_metrics_handler:
    build: .
    container_name: prusa_metrics_handler
    restart: unless-stopped
    command: 
      - "--influx-url=http://influxdb:8181"
      - "--influx-org=pubeldev"
      - "--influx-bucket=prusa"
      - "--influx-token=${INFLUXDB_TOKEN}"
      - "--prefix=prusa_"
      - "--log.level=trace"
    ports:
      - 10011:10011 # prometheus metrics
      - 8514:8514/udp
    networks:
      - pubel

  influxdb:
    container_name: influxdb3-core
    image: influxdb:3.8-core
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=${INFLUXDB_NODE_ID}
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
    volumes:
      - influxdb_data:/var/lib/influxdb3
    restart: unless-stopped
    networks:
      - pubel
    depends_on:
      - prusa_metrics_handler

  prometheus:
    image: prom/prometheus:v3.8.1
    container_name: prometheus
    restart: unless-stopped
    depends_on:
      - prusa_metrics_handler
    ports:
      - "9090:9090"
    networks:
      - pubel
    volumes:
      - ./docs/config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    networks:
      - pubel
    volumes:
      - ./docs/config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana_data:/var/lib/grafana
