
volumes:
  influxdb-data:
  grafana-data:

networks:
  pubel:

services:
  prusa_metrics_handler:
    build: .
    container_name: prusa_metrics_handler
    restart: unless-stopped
    command: 
      - "--influx-url=http://influxdb:8181"
      - "--influx-org=pubeldev"
      - "--influx-bucket=prusa"
      - "--influx-token=apiv3_wlcWHWnFU7n8ZIvbWZmBb7WFQVjyONSoXM5Y0md5w4eXYWOR0U72Y3YbUQKymZ4Bt5WSDStA9t_6huvvqSHb-g"
      - "--prefix=prusa_"
      - "--log.level=debug"
    ports:
      - 10011:10011 # prometheus metrics
      - 8514:8514/udp
    networks:
      - pubel

  influxdb:
    container_name: influxdb3-core
    image: influxdb:3.8-core
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=${INFLUXDB_NODE_ID}
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
    volumes:
      - influxdb-data:/var/lib/influxdb3
    restart: unless-stopped
    networks:
      - pubel
    depends_on:
      - prusa_metrics_handler
  
  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    networks:
      - pubel
    volumes:
      - ./docs/config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-data:/var/lib/grafana
