apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8181
    jsonData:
      version: SQL
      dbName: prusa
      httpMode: POST
      insecureGrpc: true
    secureJsonData:
      token: apiv3_9J6haftcPdn9vX0QASMT8BkdFt7IHt_pLELWI_kZEzkZCs-MVDcVAwpe0VdB_ds6vM9qgzFbFgLoWwI2xwDHRQ
  - name: prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy