apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8181
    jsonData:
      version: SQL
      dbName: prusa
      httpMode: POST
      insecureGrpc: true
    secureJsonData:
      token: <INFLUXDB_TOKEN>
  - name: prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy