apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8181
    jsonData:
      version: SQL
      dbName: prusa
      httpMode: POST
      insecureGrpc: true
    secureJsonData:
      token: apiv3_wlcWHWnFU7n8ZIvbWZmBb7WFQVjyONSoXM5Y0md5w4eXYWOR0U72Y3YbUQKymZ4Bt5WSDStA9t_6huvvqSHb-g
  - name: mimir
    type: prometheus
    url: http://mimir:9009/prometheus
    access: proxy