global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prusa_metrics_handler'
    static_configs:
      - targets: ['prusa_metrics_handler:10011']
        labels: 
          app: 'prusa_metrics_handler'
